DROP DATABASE IF EXISTS `lab2223omada8_UNIVERSITY_ADMINISTRATION_SYSTEM`;

CREATE DATABASE `lab2223omada8_UNIVERSITY_ADMINISTRATION_SYSTEM`;

USE `lab2223omada8_UNIVERSITY_ADMINISTRATION_SYSTEM`;

CREATE TABLE DEPARTMENT(`D_NAME` VARCHAR(64) NOT NULL, `D_ADDRESS` VARCHAR(256) NOT NULL, `D_EMAIL` VARCHAR(256) NOT NULL, `WEBSITE` VARCHAR(256) NOT NULL, PRIMARY KEY (`D_NAME`));

CREATE TABLE SUBJECT (`SID` INT NOT NULL, `NAME` VARCHAR(40) NOT NULL, `SEMESTER` SMALLINT NOT NULL, ECTS SMALLINT NOT NULL, PRIMARY KEY (`SID`));

CREATE TABLE PROFESSOR (`PID` INT NOT NULL, `P_FNAME` VARCHAR(20) NOT NULL, `P_LNAME` VARCHAR(20) NOT NULL, `P_EMAIL` VARCHAR(256) NOT NULL, `P_PASSWORD` VARCHAR(256), `P_ADDRESS` VARCHAR(256) NOT NULL, `P_PHONE_NUMBER` VARCHAR(16) NOT NULL, `P_TITLE` VARCHAR(20) NOT NULL, `D_NAME` VARCHAR(64), PRIMARY KEY (`PID`), FOREIGN KEY (`D_NAME`) REFERENCES DEPARTMENT(`D_NAME`));

CREATE TABLE SPECIALTY(`S_NAME` VARCHAR(64) NOT NULL, `DEPARTMENT_NAME` VARCHAR(64), PRIMARY KEY(`S_NAME`), FOREIGN KEY(`DEPARTMENT_NAME`) REFERENCES DEPARTMENT(`D_NAME`));

CREATE TABLE STUDENT (`UID` INT NOT NULL, `FNAME` VARCHAR(20) NOT NULL, `LNAME` VARCHAR(20) NOT NULL, `EMAIL` VARCHAR(256) NOT NULL, `PASSWORD` VARCHAR(256), `ADDRESS` VARCHAR(256) NOT NULL, `PHONE_NUMBER` VARCHAR(16) NOT NULL, `DATE_OF_REGISTRATION` DATE NOT NULL, `TOTAL_SUBJECTS` SMALLINT NOT NULL, `SEMESTER` SMALLINT NOT NULL, `TOTAL_ECTS` SMALLINT NOT NULL, `AVERAGE` DECIMAL(4, 2), `PASSED_SUBJECTS` SMALLINT NOT NULL, `DEPARTMENT` VARCHAR(64) NOT NULL, `SPECIALTY_NAME` VARCHAR(64), PRIMARY KEY (`UID`), FOREIGN KEY (`DEPARTMENT`) REFERENCES DEPARTMENT (`D_NAME`), FOREIGN KEY (`SPECIALTY_NAME`) REFERENCES SPECIALTY (`S_NAME`));

CREATE TABLE REGISTERS_FOR( `REG_ID` INT NOT NULL AUTO_INCREMENT , `STUDENT_UID` INT NOT NULL , `SUBJECT_ID` INT NOT NULL , PRIMARY KEY (`REG_ID`), FOREIGN KEY (`STUDENT_UID`) REFERENCES STUDENT(`UID`), FOREIGN KEY (`SUBJECT_ID`) REFERENCES SUBJECT(`SID`));

CREATE TABLE EXAM_GRADES(`REG_ID` INT NOT NULL, `EXAM_PERIOD` VARCHAR(20) NOT NULL, `GRADE` DECIMAL(4, 2), PRIMARY KEY (`REG_ID`, `EXAM_PERIOD`), FOREIGN KEY (`REG_ID`) REFERENCES REGISTERS_FOR(`REG_ID`));

CREATE TABLE THESIS (`TITLE` VARCHAR(64) NOT NULL, `DUE_DATE` DATE NOT NULL, `GRADE` DECIMAL(4, 2), `STATUS` VARCHAR(20) NOT NULL, `STUDENT_UID` INT, `DATE_OF_UNDERTAKING` DATE, `PROFESSOR_UID` INT NOT NULL, PRIMARY KEY (`TITLE`), FOREIGN KEY (`STUDENT_UID`) REFERENCES STUDENT (`UID`), FOREIGN KEY (`PROFESSOR_UID`) REFERENCES PROFESSOR (`PID`));

CREATE TABLE TEACHES (`SID` INT NOT NULL, `PID` INT NOT NULL, PRIMARY KEY (`SID`,`PID`), FOREIGN KEY (`SID`) REFERENCES SUBJECT(`SID`), FOREIGN KEY (`PID`) REFERENCES PROFESSOR(`PID`)); 

CREATE TABLE GRADES (`THESIS_TITLE` VARCHAR(64) NOT NULL,`PID` INT NOT NULL,`GRADE` DECIMAL(4,2), PRIMARY KEY (`THESIS_TITLE`,`PID`),FOREIGN KEY (`PID`) REFERENCES PROFESSOR(`PID`)); 

CREATE TABLE DEPARTMENT_PHONE_NUMBERS (`D_NAME` VARCHAR(64) NOT NULL, `PHONE_NUMBER` VARCHAR(16) NOT NULL, PRIMARY KEY (`PHONE_NUMBER`), FOREIGN KEY (`D_NAME`) REFERENCES DEPARTMENT(`D_NAME`));

CREATE TABLE IS_PART_OF(`SID` INT NOT NULL, `S_NAME` VARCHAR(64) NOT NULL, TYPE VARCHAR(32), PRIMARY KEY (`SID`, `S_NAME`), FOREIGN KEY (`SID`) REFERENCES SUBJECT(`SID`), FOREIGN KEY (`S_NAME`) REFERENCES SPECIALTY(`S_NAME`));

CREATE TABLE LOG_TABLE ( `ID` INT NOT NULL AUTO_INCREMENT , `MSG` VARCHAR(512) NOT NULL , PRIMARY KEY (`ID`));
