-- Indexes
CREATE INDEX STUDENTS_LAST_NAME ON STUDENT(LNAME);
CREATE INDEX SUBJECT_SEM ON SUBJECT(SEMESTER);

-- Views
CREATE VIEW EL_ENG_STUDENTS AS SELECT UID, FNAME, LNAME, EMAIL, SEMESTER, SPECIALTY_NAME FROM STUDENT WHERE DEPARTMENT = 'DEPARTMENT OF ELECTRICAL ENGINEERING';
CREATE VIEW STUDENT_GRADES AS SELECT rf.STUDENT_UID, rf.SUBJECT_ID, eg.EXAM_PERIOD, eg.GRADE FROM REGISTERS_FOR rf, EXAM_GRADES eg WHERE rf.REG_ID=eg.REG_ID;

-- Debug procedure
DELIMITER //
CREATE PROCEDURE LOG_MSG(msg VARCHAR(512))
BEGIN
    INSERT INTO `LOG_TABLE` (`MSG`) VALUES (msg);
END; //
DELIMITER ;

-- Procedure to Update STUDENT.AVERAGE
DELIMITER //
CREATE PROCEDURE UPDATE_AVERAGE (IN reg_id SMALLINT)
BEGIN
    SET @student_uid = (SELECT rf.STUDENT_UID FROM REGISTERS_FOR rf WHERE rf.REG_ID=reg_id);
    UPDATE STUDENT SET AVERAGE = ( SELECT AVG(eg.GRADE) FROM REGISTERS_FOR rf LEFT OUTER JOIN EXAM_GRADES eg ON rf.REG_ID=eg.REG_ID WHERE rf.STUDENT_UID=@student_uid AND eg.GRADE>=5 ) WHERE UID=@student_uid;
END//
DELIMITER ;

-- Triggers to Update STUDENT.AVERAGE
DELIMITER //
CREATE TRIGGER UPDATE_STUDENT_AVERAGE_INSERT
AFTER INSERT
ON EXAM_GRADES
FOR EACH ROW
BEGIN
    CALL UPDATE_AVERAGE(NEW.REG_ID);
END //
DELIMITER ;

DELIMITER //
CREATE TRIGGER UPDATE_STUDENT_AVERAGE_UPDATE
AFTER UPDATE
ON EXAM_GRADES
FOR EACH ROW
BEGIN
    CALL UPDATE_AVERAGE(OLD.REG_ID);
    IF (OLD.REG_ID != NEW.REG_ID) THEN
    CALL UPDATE_AVERAGE(NEW.REG_ID);
    END IF;
END //
DELIMITER ;

DELIMITER //
CREATE TRIGGER UPDATE_STUDENT_AVERAGE_DELETE
AFTER DELETE
ON EXAM_GRADES
FOR EACH ROW
BEGIN
    CALL UPDATE_AVERAGE(OLD.REG_ID);
END //
DELIMITER ;



-- Get ECTS from REG_ID
DELIMITER //
CREATE FUNCTION RegECTS (reg_id INT)
   RETURNS SMALLINT
   BEGIN
   RETURN (SELECT s.ECTS FROM SUBJECT s WHERE s.SID=(SELECT rf.SUBJECT_ID FROM REGISTERS_FOR rf WHERE rf.REG_ID=reg_id));
END; //
DELIMITER ;

-- Procedure to Update STUDENT.ECTS
DELIMITER //
CREATE PROCEDURE STUDENT_ECTS
(IN action_in VARCHAR(6), IN reg_in INT, IN grade_in DECIMAL(4,2))
BEGIN
    IF action_in= 'INSERT' AND grade_in>=5 THEN
        SET @student_uid = (SELECT rf.STUDENT_UID FROM REGISTERS_FOR rf WHERE rf.REG_ID=reg_in);
        UPDATE STUDENT SET TOTAL_ECTS = TOTAL_ECTS + RegECTS(reg_in) WHERE UID=@student_uid;
    ELSEIF action_in= 'DELETE' AND grade_in>=5 THEN
        SET @student_uid = (SELECT rf.STUDENT_UID FROM REGISTERS_FOR rf WHERE rf.REG_ID=reg_in);
        UPDATE STUDENT SET TOTAL_ECTS = TOTAL_ECTS - RegECTS(reg_in) WHERE UID=@student_uid;
    END IF;
END//
DELIMITER ;

-- Triggers to Update STUDENT.ECTS
DELIMITER //
CREATE TRIGGER STUDENT_TOTAL_ECTS_INSERT
AFTER INSERT
ON EXAM_GRADES
FOR EACH ROW
BEGIN
    CALL STUDENT_ECTS('INSERT', NEW.REG_ID, NEW.GRADE);
END//
DELIMITER ;

DELIMITER //
CREATE TRIGGER STUDENT_TOTAL_ECTS_DELETE
AFTER DELETE
ON EXAM_GRADES
FOR EACH ROW
BEGIN
    CALL STUDENT_ECTS('DELETE', OLD.REG_ID, OLD.GRADE);
END//
DELIMITER ;

DELIMITER //
CREATE TRIGGER STUDENT_TOTAL_ECTS_UPDATE
AFTER UPDATE
ON EXAM_GRADES
FOR EACH ROW
BEGIN
    SET @student_uid = (SELECT rf.STUDENT_UID FROM REGISTERS_FOR rf WHERE rf.REG_ID=NEW.REG_ID);
    IF NEW.GRADE>=5 AND OLD.GRADE>=5 THEN
    UPDATE STUDENT SET TOTAL_ECTS = TOTAL_ECTS - RegECTS(OLD.REG_ID) + RegECTS(NEW.REG_ID) WHERE UID=@student_uid;
    ELSEIF NEW.GRADE>=5 AND OLD.GRADE<=5 THEN
    UPDATE STUDENT SET TOTAL_ECTS = TOTAL_ECTS + RegECTS(NEW.REG_ID) WHERE UID=@student_uid;
    ELSEIF NEW.GRADE<=5 AND OLD.GRADE>=5 THEN
    UPDATE STUDENT SET TOTAL_ECTS = TOTAL_ECTS - RegECTS(OLD.REG_ID) WHERE UID=@student_uid;
    END IF;
END//
DELIMITER ;

-- Procedure to Update STUDENT.TOTAL_SUBJECTS
DELIMITER //
CREATE PROCEDURE UPDATE_TOTAL_SUBJECTS (student_uid INT)
BEGIN
    call LOG_MSG(concat_ws('', 'Started proc UPDATE_TOTAL_SUBJECTS student_id=', student_uid));
    SET @total_subjects = (SELECT COUNT(DISTINCT rf.SUBJECT_ID) FROM REGISTERS_FOR rf WHERE rf.STUDENT_UID=student_uid);
    call LOG_MSG(concat_ws('','total_subjects:', @total_subjects));
    UPDATE STUDENT s SET s.TOTAL_SUBJECTS = @total_subjects WHERE s.UID=student_uid;
    call LOG_MSG('Finished proc UPDATE_TOTAL_SUBJECTS');
END//
DELIMITER ;

-- Update STUDENT.TOTAL_SUBJECTS [ACTION]
DELIMITER //
CREATE TRIGGER UPDATE_TOTAL_SUBJECTS_INSERT
AFTER INSERT
ON REGISTERS_FOR
FOR EACH ROW
BEGIN
CALL UPDATE_TOTAL_SUBJECTS(NEW.STUDENT_UID);
END //
DELIMITER ;

DELIMITER //
CREATE TRIGGER UPDATE_TOTAL_SUBJECTS_UPDATE
AFTER UPDATE
ON REGISTERS_FOR
FOR EACH ROW
BEGIN
CALL UPDATE_TOTAL_SUBJECTS(NEW.STUDENT_UID);
IF (NEW.STUDENT_UID != OLD.STUDENT_UID) THEN
    CALL UPDATE_TOTAL_SUBJECTS(OLD.STUDENT_UID);
END IF;
END //
DELIMITER ;

DELIMITER //
CREATE TRIGGER UPDATE_TOTAL_SUBJECTS_DELETE
AFTER DELETE
ON REGISTERS_FOR
FOR EACH ROW
BEGIN
CALL UPDATE_TOTAL_SUBJECTS(OLD.STUDENT_UID);
END //
DELIMITER ;

